# Generated by Django 6.1.1 on 2026-09-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
